# permissions for end users to view resourcetopologyexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcetopologyexporter-viewer-role
rules:
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - resourcetopologyexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - resourcetopologyexporters/status
  verbs:
  - get
