# permissions for end users to edit RTEOperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rteoperator-editor-role
rules:
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - rteoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - rteoperators/status
  verbs:
  - get
