# permissions for end users to view RTEOperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rteoperator-viewer-role
rules:
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - rteoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topologyexporter.openshift-kni.io
  resources:
  - rteoperators/status
  verbs:
  - get
