kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topology-aware-controller
subjects:
- kind: ServiceAccount
  name: topology-aware-controller
  namespace: tas-scheduler
roleRef:
  kind: ClusterRole
  name: topology-aware-controller
  apiGroup: rbac.authorization.k8s.io

