name: CI Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout=15m0s --verbose

  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: format
      run: ./hack/check-format.sh

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Verify modules
      run: go mod verify

    - name: Vetting
      run: make vet

    - name: Build operand
      run: make binary

    - name: Build operator
      run: make binary-rte

    - name: Run unit tests
      run: make test-unit
